version: 1
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude-files:
    - ".*_test\\.go"
    - "di/wire_gen.go"
  exclude-dirs:
    - "internal/adapters/repositories/mocks"

run:
  timeout: 3m